### ISSUE TITLE
numpy 2 support

### ISSUE THREAD

**Issue by xmatthias** [roebel/py_find_1st#14]
Hi,

when Using this library with numpy2, the following error comes up:

Reproduction:

`pip install py_find_1st "numpy>=2"`

```
$ python
Python 3.12.2 (main, Mar 14 2024, 18:27:18) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import utils_find_1st

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/home/xmatt/.pyenv/versions/trade_3122/lib/python3.12/site-packages/utils_find_1st/__init__.py", line 3, in <module>
    from .find_1st import find_1st
Traceback (most recent call last):
  File "/home/xmatt/.pyenv/versions/trade_3122/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xmatt/.pyenv/versions/trade_3122/lib/python3.12/site-packages/utils_find_1st/__init__.py", line 3, in <module>
    from .find_1st import find_1st 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: numpy.core.multiarray failed to import
```

Now based on the error, this MAY be just a question of "rebuild the C module" only (and re-release i guess) - but maybe there's more work needed (i'm not into numpy module development to be able to determine this).

(as a side note: it might be good to pin numpy to <3.0 in the installation - with the assumption that 3.0 will have ABI incompatibilities again).

**Comment by roebel** [comment]
Hello, and thanks for the bug report.

the problem here is the build dependency to oldest-supported-numpy in the pyproject.toml file. The oldest-supported-numpy package was required for numpy < 1.25 but is now deprecated because it cannot be used with numpy > version 2. I think I have fixed the problem, and it still works for my numpy installs with numpy version 1. I can not check with numpy 2. Can you try the 1.1.7 release candidate 4 from test.pypi.org? 
You would install it like this:

```
pip install --no-cache-dir --extra-index-url https://test.pypi.org/simple/ py_find_1st==1.1.7rc4
```

You wrote:

```
(as a side note: it might be good to pin numpy to <3.0 in the installation - with the assumption that 3.0 will have ABI incompatibilities again).
```

Good point, I now use this for the runtime dependencies in pyproject.toml

```
dependencies = [
    "numpy>=1.13.0,<2.0; python_version<='3.8'",
    "numpy>=1.19.3,<3; python_version>'3.8'",
]
```

Best

**Comment by xmatthias** [comment]
thanks a lot for your work and very quick help (over the holidays, too!)!

i've ran a few tests with rc4 - mostly based on examples in the readme, as well as my own usage - and it seems to work fine with both numpy<2 and numpy>2 (i've used the latest numpy, but i assume it'll work with every 2.x version).

**Comment by roebel** [comment]
Ok, thanks, I have published the version 1.1.7.
